name: PR Check

on:
  # Runs on pull request events that target one of the below branches
  pull_request:
    types: [opened, reopened, synchronize]

env:
  # Ensures Python uses UTF-8 encoding by default
  PYTHONUTF8: 1

  # Disables rich text formatting in Flet CLI output
  FLET_CLI_NO_RICH_OUTPUT: 1

  # Disables progress bars when using UV
  UV_NO_PROGRESS: 1


jobs:
  check:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Initialize the project
      run: uv sync --no-default-groups --group check

    - name: Lint check
      run: uv run ruff check .

    - name: Format check
      run: uv run ruff format --check --diff

    - name: Type check
      run: uv run mypy .

    - name: Test
      run: uv run pytest

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Initialize the project
      run: uv sync --no-default-groups --build

    - name: Build flet app
      run: uv run flet build windows --verbose --no-rich-output

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: windows-build
        path: build/windows
        if-no-files-found: error
        overwrite: false